# The fraction of the new image that will enter the collage.
alpha: 0.2

# These should be roughly square for good behavior.
display_width: 1024
display_height: 1280

# How many faces should be "remembered" before a repeat is allowed.
face_memory: 10

# Larger values mean the algorithm is more likely to say it has seen the face before.
tolerance: 0.4
